// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs5faVouIkZm-YyITeeAbja6nlpg1O6c0',
    appId: '1:718092694581:android:12ea2e2b86ee1bae4fad7c',
    messagingSenderId: '718092694581',
    projectId: 'flutter1-af24f',
    storageBucket: 'flutter1-af24f.appspot.com',
  );



  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrZpexWamtz8EApGY3dNkyKFTkdCa2vk',
    appId: '1:718092694581:ios:8d7b08c022668b9a4fad7c',
    messagingSenderId: '990705702621',
    projectId: 'flutter1-af24f',
    storageBucket: 'flutter1-af24f.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGbgUyOmc2qI5391UtUxBw0ko7jXpC9FI',
    appId: '1:718092694581:ios:8d7b08c022668b9a4fad7c',
    messagingSenderId: '718092694581',
    projectId: 'flutter1-af24f',
  );

}
